import Head from "next/head";
import Image from "next/image";
import Ripples from "../Components/Ripples";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='anim'>
        <Ripples paddingX={0} paddingY={0} />
      </div>
    </div>
  );
}
